export const _user = {
  name: "John Doe",
  firstName: "John",
  lastName: "Doe",
  email: "jogn@gmail.com",
  phone: "1234567890",
  address: "123 Main St, City, Country",
  dateOfBirth: "1990-01-01",
  role: "Student",
  departments: [
    { departmentName: "Computer Engineering" },
    {
      departmentName: "Computer Science",
    },
  ],
};

export const _program = "Computer Engineering";

export const _studentSubjects = [
  {
    courseCode: "CS101",
    courseName: "Introduction to Computer Science",
    credits: 3,
    akts: 6,
    attendanceStatus: "Completed",
    passGrade: "AA",
    lpg: 4.0,
    standing: "Passed",
    midTerm: 90,
    final: 95,
    complement: 92,
  },
  {
    courseCode: "MATH204",
    courseName: "Linear Algebra",
    credits: 4,
    akts: 7,
    attendanceStatus: "Completed",
    passGrade: "BA",
    lpg: 3.5,
    standing: "Passed",
    midTerm: 85,
    final: 88,
    complement: 87,
  },
  {
    courseCode: "PHY111",
    courseName: "Physics I",
    credits: 4,
    akts: 6,
    attendanceStatus: "Missed 1 class",
    passGrade: "CB",
    lpg: 2.5,
    standing: "Passed",
    midTerm: 70,
    final: 65,
    complement: 68,
  },
  {
    courseCode: "ENG102",
    courseName: "Academic Writing",
    credits: 2,
    akts: 3,
    attendanceStatus: "Completed",
    passGrade: "BB",
    lpg: 3.0,
    standing: "Passed",
    midTerm: 80,
    final: 78,
    complement: 79,
  },
  {
    courseCode: "HIST210",
    courseName: "Modern History",
    credits: 3,
    akts: 5,
    attendanceStatus: "Incomplete",
    passGrade: "F",
    lpg: 0.0,
    standing: "Failed",
    midTerm: 40,
    final: 35,
    complement: 38,
  },
];
